version: "3"

services:
  app:
    build: .
    container_name: sudoku-solver
    tty: true
    volumes:
      - .:/go/src/app
    ports: 
      - 8080:8080
    working_dir: /go/src/app
    command: "realize start --run"