version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: sudoku-solver
    volumes:
      - .:/go/src/github.com/Fukkatsuso/sudoku-solver-app
    ports:
      - 8080:8080
    working_dir: /go/src/github.com/Fukkatsuso/sudoku-solver-app
